"use client"

import { useState } from "react"
import { motion } from "framer-motion"
import { ArrowLeft, ArrowRight, ChevronDown, ChevronLeft, Headphones, Heart, Instagram, Leaf, Mail, MapPin, Menu, Search, ShieldCheck, ShoppingBag, Truck, UserRound, X } from "lucide-react"

const sourceImages: Record<string, string> = {
  "photo-1518199266791-5375a83190b7": "/source-images/c0.jpg",
  "photo-1464349095431-e9a21285b5f3": "/source-images/c4.jpg",
  "photo-1531058020387-3be344556be6": "/source-images/c2.jpg",
  "photo-1519689680058-324335c77eba": "/source-images/c5.jpg",
  "photo-1490750967868-88aa4486c946": "/source-images/c1.jpg",
  "photo-1549465220-1a8b9238cd48": "/source-images/c3.jpg",
  "photo-1523438885200-e635ba2c371e": "/source-images/c1.jpg",
  "photo-1522673607200-164d1b6ce486": "/source-images/c5.jpg",
  "photo-1518895949257-7621c3c786d7": "/source-images/c2.jpg",
  "photo-1561181286-d3fee7d55364": "/source-images/c0.jpg",
  "photo-1512909006721-3d6018887383": "/source-images/c3.jpg",
}
const image = (id: string, _w?: number, _h?: number) => id === "van" ? "/source-images/van.jpg" : id.startsWith("asset-") ? `/source-images/${id.replace("asset-", "")}.jpg` : sourceImages[id] ?? "/source-images/3.jpg"
const categories = [
  ["للحب والرومانسية", "photo-1518199266791-5375a83190b7"], ["أعياد الميلاد", "photo-1464349095431-e9a21285b5f3"], ["مبروك وتخرج", "photo-1531058020387-3be344556be6"], ["مواليد", "photo-1519689680058-324335c77eba"], ["شكر وتقدير", "photo-1490750967868-88aa4486c946"], ["هدايا فاخرة", "photo-1549465220-1a8b9238cd48"],
]
const products = [
  ["باقة السعادة", "مزيج من الألوان الزاهية", "149 ر.س", "asset-10", "جديد"], ["باقة المشاعر", "ورد أحمر مع لمسات من الجبسوفيلا", "179 ر.س", "asset-11", "الأكثر مبيعاً"], ["باقة النقاء", "ورد أبيض فاخر وبسيط", "249 ر.س", "asset-12", "جديد"], ["باقة الأناقة", "مزيج من الورد والزهور الموسمية", "199 ر.س", "asset-13", "الأكثر مبيعاً"], ["باقة احب الحب", "ورد أحمر فاخر مع لمسات بيضاء", "299 ر.س", "asset-14", "الأكثر مبيعاً"],
]
const features = [[FlowerIcon, "جودة مضمونة", "أزهار طازجة وتنسيقات مميزة"], [Truck, "توصيل سريع", "لجميع مناطق المملكة"], [ShieldCheck, "دفع آمن", "بجميع طرق الدفع"], [Headphones, "خدمة عملاء متميزة", "من 8 صباحاً حتى 12 مساءً"]]
function FlowerIcon({className}: {className?: string}) { return <Leaf className={className} /> }

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [cart, setCart] = useState(0)
  const [favorites, setFavorites] = useState<number[]>([])
  const [search, setSearch] = useState("")
  const [email, setEmail] = useState("")
  const filtered = products.filter(p => p[0].includes(search) || p[1].includes(search))
  return <main>
    <div className="border-b border-[#f3eaec] text-xs font-medium text-[#444]">
      <div className="mx-auto flex h-10 w-[91%] max-w-[1200px] items-center justify-between"><div className="hidden items-center gap-6 md:flex"><span>المملكة العربية السعودية</span><span className="flex items-center gap-1"><MapPin className="size-3.5 text-[#95264e]" /> توصيل لجميع مناطق المملكة</span></div><div className="mx-auto flex items-center gap-5 md:mx-0"><button className="relative flex items-center gap-1" aria-label="السلة"><ShoppingBag className="size-4 text-[#95264e]" /> السلة <b className="grid size-4 place-items-center rounded-full bg-[#95264e] text-[9px] text-white">{cart}</b></button><button className="flex items-center gap-1"><Heart className="size-4 text-[#95264e]" /> المفضلة</button><button className="hidden items-center gap-1 sm:flex"><UserRound className="size-4 text-[#95264e]" /> تسجيل الدخول / إنشاء حساب</button></div></div>
    </div>
    <header className="relative border-b border-[#f7edef] bg-white"><div className="mx-auto flex w-[91%] max-w-[1200px] flex-wrap items-center gap-3 py-2 md:h-[72px] md:flex-nowrap md:gap-8 md:py-0"><a href="#" className="flex items-center" aria-label="لولي روز"><img src="/source-images/flogo.jpg" alt="لولي روز" className="h-[54px] w-auto object-contain" /></a><button className="mr-auto grid size-10 place-items-center rounded-lg bg-[#fcf0f2] text-[#95264e] md:hidden" aria-label="القائمة" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button><nav className={`${menuOpen ? "flex" : "hidden"} order-3 w-full flex-col gap-0 border-t border-[#efe1e5] bg-white py-2 md:order-none md:flex md:w-auto md:flex-row md:gap-7 md:border-0 md:py-0`}><a className="border-b-2 border-[#95264e] py-3 font-bold text-[#95264e] md:border-0" href="#">الرئيسية</a><a className="flex items-center gap-1 border-b border-[#f5ecee] py-3 font-semibold md:border-0" href="#products">المنتجات <ChevronDown className="size-4" /></a><a className="border-b border-[#f5ecee] py-3 font-semibold md:border-0" href="#gifts">الهدايا</a><a className="border-b border-[#f5ecee] py-3 font-semibold md:border-0" href="#offers">عروض خاصة</a><a className="border-b border-[#f5ecee] py-3 font-semibold md:border-0" href="#about">من نحن</a><a className="py-3 font-semibold" href="#contact">تواصل معنا</a></nav><label className="order-4 flex h-10 w-full items-center rounded-full border border-[#ecdde1] px-3 shadow-sm shadow-[#95264e]/5 md:order-none md:mr-auto md:w-[270px]"><input value={search} onChange={e => setSearch(e.target.value)} placeholder="ابحث عن باقة أو منتج..." className="min-w-0 flex-1 bg-transparent text-xs outline-none" /><button aria-label="بحث" className="grid size-7 place-items-center rounded-full bg-[#95264e] text-white"><Search className="size-4" /></button></label></div></header>
    <section className="relative overflow-hidden bg-gradient-to-l from-[#fdf4f1] via-[#fae8e2] to-[#f1d6d0]"><div className="absolute inset-y-0 left-0 w-[62%] bg-[url('/source-images/3.jpg')] bg-cover bg-center opacity-100 [mask-image:linear-gradient(to_right,black,transparent)]" /><div className="relative mx-auto flex min-h-[304px] w-[91%] max-w-[1200px] items-center justify-start"><motion.div initial={{opacity:1,x:0}} animate={{opacity:1,x:0}} transition={{duration:.7}} className="relative z-10 max-w-lg text-right"><p className="mb-2 font-semibold text-[#95264e]">أزهار تنطق بالمشاعر</p><h1 className="text-2xl font-bold leading-[1.45] text-[#2b2a38] md:text-4xl">أجمل باقات الورد والهدايا<br />لجميع مناسباتك</h1><p className="mt-3 max-w-md text-sm font-medium leading-8 text-[#4a4655]">نختار لك أجمل الورود والهدايا بتنسيقات عصرية وجودة عالية مع خدمة توصيل سريعة وآمنة في جميع مناطق المملكة.</p><a href="#products" className="mt-5 inline-flex items-center gap-2 rounded-lg bg-[#95264e] px-6 py-3 text-sm font-semibold text-white shadow-lg shadow-[#95264e]/25 transition hover:bg-[#7a1d3f]">تسوق الآن <ArrowLeft className="size-4" /></a></motion.div></div><div className="absolute bottom-4 left-1/2 flex -translate-x-1/2 gap-2"><i className="size-2 rounded-full bg-[#95264e]" /><i className="size-2 rounded-full bg-white" /><i className="size-2 rounded-full bg-white" /></div></section>
    <div className="mx-auto w-[91%] max-w-[1200px]"><div className="grid grid-cols-2 gap-2 rounded-xl border border-[#f5e7ea] bg-[#fcf5f6] p-3 md:grid-cols-4 md:gap-0">{features.map(([Icon,title,desc], i) => <div key={title as string} className={`flex items-center gap-3 p-3 ${i > 1 ? "md:border-r md:border-[#ecdce0]" : i > 0 ? "md:border-r md:border-[#ecdce0]" : ""}`}><Icon className="size-8 shrink-0 text-[#95264e]" /><div><b className="block text-xs font-semibold">{title as string}</b><span className="text-[10px] font-medium text-[#625b6b]">{desc as string}</span></div></div>)}</div>
      <section className="mt-7"><SectionTitle title="تسوق حسب المناسبة" subtitle="اختر المناسبة التي تناسبك" action="عرض الكل" /> <div className="grid grid-cols-2 gap-2 sm:grid-cols-3 md:grid-cols-6">{categories.map(([title,src], i) => <motion.a whileHover={{y:-4}} key={title} href="#products" className="relative rounded-lg bg-[#fcf3f5] p-3 text-center text-xs font-semibold shadow-sm transition hover:shadow-lg hover:shadow-[#95264e]/10"><img src={image(src,180,130)} alt="" className="mx-auto mb-2 h-16 w-full rounded-md object-cover" /><span>{title}</span>{i===0 && <span className="absolute left-2 top-2 grid size-5 place-items-center rounded-full bg-white text-[#95264e]"><ArrowRight className="size-3" /></span>}</motion.a>)}</div></section>
      <section id="products" className="mt-10"><SectionTitle title="أكثر المنتجات مبيعاً" subtitle="اختيارات عملائنا المفضلة" /><div className="mt-3 h-1 w-16 rounded bg-[#95264e]" /><div className="mt-5 grid grid-cols-1 gap-4 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-5">{(filtered.length ? filtered : products).map(([title,desc,price,src,badge],i) => <motion.article initial={{opacity:0,y:15}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.05}} key={title} className="overflow-hidden rounded-xl border border-[#f1e8ea] bg-white text-center shadow-sm transition hover:-translate-y-1 hover:shadow-xl hover:shadow-black/10"><div className="relative"><img src={image(src)} alt={title} className="h-40 w-full object-cover" /><span className={`absolute left-2 top-2 rounded bg-[#95264e] px-2 py-1 text-[10px] font-semibold text-white ${badge === "جديد" ? "bg-[#3a3947]" : ""}`}>{badge}</span><button onClick={() => setFavorites(favorites.includes(i) ? favorites.filter(x => x!==i) : [...favorites,i])} aria-label="إضافة للمفضلة" className="absolute right-2 top-2 grid size-8 place-items-center rounded-full bg-white text-[#95264e] shadow"><Heart className={`size-4 ${favorites.includes(i) ? "fill-current" : ""}`} /></button></div><div className="p-3"><h3 className="text-sm font-semibold">{title}</h3><p className="mt-1 text-[10px] font-medium text-[#625b6b]">{desc}</p><strong className="mt-1 block text-base font-semibold text-[#2b2a38]">{price}</strong><button onClick={() => setCart(cart+1)} className="mt-2 flex h-8 w-full items-center justify-center gap-2 rounded-md bg-[#95264e] text-xs font-semibold text-white transition hover:bg-[#7a1d3f]"><ShoppingBag className="size-3.5" /> أضف للسلة</button></div></motion.article>)}</div></section>
      <section id="offers" className="mt-8 grid gap-4 md:grid-cols-2"><Promo title="اجعل مناسبتك أجمل" text="أضيفي لمستك الخاصة مع بطاقات الهدايا والتغليف المميز" src="asset-19" /><Promo title="توصيل سريع وآمن" text="نوصل طلبك في جميع مدن المملكة بأمان واهتمام" src="van" /></section>
      <section id="contact" className="my-4 flex flex-col items-start justify-between gap-3 rounded-xl bg-gradient-to-l from-[#fcf1f2] to-[#f0b4c0] px-6 py-4 sm:flex-row sm:items-center"><div><h3 className="font-bold text-[#7a1d3f]">اشترك في نشرتنا البريدية</h3><p className="text-xs text-[#5b5561]">كوني أول من يعرف عن عروضنا وتنسيقاتنا الجديدة</p></div><form onSubmit={e => {e.preventDefault(); setEmail("")}} className="flex h-10 w-full overflow-hidden rounded-full bg-white sm:w-[340px]"><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="بريدك الإلكتروني" className="min-w-0 flex-1 px-4 text-xs outline-none" /><button className="bg-[#95264e] px-5 text-xs font-semibold text-white">اشتراك</button></form></section>
      <footer id="about" className="relative overflow-hidden border-t border-[#efe1e5] py-7"><img src="/source-images/roseR.jpg" alt="" aria-hidden="true" className="pointer-events-none absolute right-0 top-0 h-full w-16 object-cover opacity-60" /><div className="relative grid gap-7 sm:grid-cols-2 md:grid-cols-4"><div><div className="flex items-center gap-2 text-xl font-bold text-[#95264e]"><span className="grid size-9 place-items-center rounded-full bg-[#fcf0f2]"><Leaf className="size-5" /></span>لولي <em className="not-italic text-[#c87891]">روز</em></div><p className="mt-3 text-xs leading-6 text-[#575160]">نصنع لحظاتكم الجميلة بباقات ورد وهدايا تعبّر عن مشاعركم.</p><div className="mt-3 flex gap-2"><a className="grid size-7 place-items-center rounded-full bg-[#f5e8ec] text-[#95264e]" href="#"><Instagram className="size-4" /></a><a className="grid size-7 place-items-center rounded-full bg-[#f5e8ec] text-[#95264e]" href="#"><Mail className="size-4" /></a></div></div><FooterList title="روابط سريعة" items={["الرئيسية","المنتجات","العروض الخاصة","من نحن"]} /><FooterList title="خدمة العملاء" items={["تواصل معنا","سياسة الشحن","الأسئلة الشائعة","سياسة الاستبدال"]} /><div><h4 className="mb-3 text-sm font-bold">تواصلي معنا</h4><p className="text-xs leading-7 text-[#575160]">الرياض، المملكة العربية السعودية<br />+966 55 123 4567<br />hello@lollyrose.sa</p></div></div><div className="relative mt-6 flex flex-col items-center gap-3 border-t border-[#efe1e5] pt-4 text-center text-[10px] text-[#6b6572]"><img src="/source-images/pay.jpg" alt="طرق الدفع المتاحة" className="h-auto w-40 object-contain" /><span>© 2024 لولي روز. جميع الحقوق محفوظة.</span></div></footer>
    </div>
  </main>
}
function SectionTitle({title,subtitle,action}:{title:string,subtitle:string,action?:string}) { return <div className="flex items-start justify-between"><div><h2 className="flex items-center gap-2 text-lg font-bold md:text-xl"><span className="h-1 w-4 rounded bg-[#95264e]" />{title}</h2><p className="mr-6 mt-1 text-[10px] text-[#6f6874]">{subtitle}</p></div>{action && <a href="#products" className="flex items-center gap-1 rounded-md bg-[#fcf0f2] px-3 py-2 text-xs font-semibold text-[#95264e]">{action}<ChevronLeft className="size-3" /></a>}</div> }
function Promo({title,text,src}:{title:string,text:string,src:string}) { return <div className="relative min-h-36 overflow-hidden rounded-xl border border-[#f6e6e9] bg-[#fbefef] p-5"><img src={image(src,500,300)} alt="" className="absolute inset-y-0 left-0 h-full w-1/2 object-cover [mask-image:linear-gradient(to_right,black,transparent)]" /><div className="relative max-w-[55%]"><h3 className="font-bold text-[#7a1d3f]">{title}</h3><p className="mt-1 text-xs leading-6 text-[#5b5561]">{text}</p><a href="#products" className="mt-2 inline-flex items-center gap-2 rounded-md bg-[#95264e] px-4 py-2 text-xs text-white">تسوقي الآن <ArrowLeft className="size-3" /></a></div></div> }
function FooterList({title,items}:{title:string,items:string[]}) { return <div><h4 className="mb-3 text-sm font-bold">{title}</h4><ul className="flex flex-col gap-2 text-xs text-[#575160]">{items.map(item=><li key={item}><a href="#">{item}</a></li>)}</ul></div> }
